# Generated by Django 5.0.1 on 2024-02-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, upload_to='book_covers'),
        ),
    ]
