# Generated by Django 5.0.1 on 2024-02-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_book_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_cover',
        ),
    ]
