# Generated by Django 5.0.1 on 2024-02-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0007_remove_book_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
