# Generated by Django 4.2.3 on 2024-02-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0011_author_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
