# Generated by Django 4.2.3 on 2024-02-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0015_author_born'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='died',
            field=models.DateField(blank=True, null=True),
        ),
    ]
